### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by RayhanTabase** [thecodechaser/leaderboard#4]
### We think that these optional changes could help make your project even better;
- You could consider arranging the scores list in order of highest score

**Comment by thecodechaser** [comment]
> ### Your project looks amazing 👍👍🎉🎉🎉. Everything works as expected.
> ### We think that these optional changes could help make your project even better;
> * You could consider arranging the scores list in order of highest score

Hello @RayhanTabase 👋 
Thank you for your feedback, Your suggestion looks great and I will implement this functionality ASAP!

**Comment by anuarshaidenov** [comment]
## Well done, @thecodechaser!
I really love how you kept your code clean and separated the functions🥶

**Comment by thecodechaser** [comment]
> ## Well done, @thecodechaser!
> I really love how you kept your code clean and separated the functions🥶

## Hello @anuarshaidenov 
Thank you for your feedback.
